import React, { useMemo, useState, useEffect } from 'react';
import { Alert, Row, Col, Card, Accordion, Badge, Button, Spinner, Form, ProgressBar } from 'react-bootstrap';
import { useRecommendations } from '../contexts/RecommendationContext';
import GradesChart from '../components/GradesChart';
import CoursesChart from '../components/CoursesChart';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext'; // Import useAuth

// --- Helper Component for Detail Rows ---
const DetailRow = ({ title, content }: { title: string; content: string }) => (
  <p><strong>{title}:</strong> {content}</p>
);

// --- Star Rating Component ---
const StarRating = ({ rating, setRating }: { rating: number; setRating: (rating: number) => void }) => {
  return (
    <div>
      {[1, 2, 3, 4, 5].map((star) => (
        <span
          key={star}
          style={{ cursor: 'pointer', color: star <= rating ? 'gold' : 'gray', fontSize: '30px' }}
          onClick={() => setRating(star)}
        >
          ★
        </span>
      ))}
    </div>
  );
};


const ReportPage: React.FC = () => {
  const { recommendations, isLoading } = useRecommendations();
  const { token } = useAuth(); // Get token from AuthContext
  const topCourse = useMemo(() => recommendations?.courses[0], [recommendations]);
  const topCareer = useMemo(() => recommendations?.careers[0], [recommendations]); // New: Top career
  const [ratings, setRatings] = useState<{ [id: number]: number }>({});
  const [comments, setComments] = useState<{ [id: number]: string }>({});
  const [averageRatings, setAverageRatings] = useState<{ [id: number]: { avg: number; count: number } }>({});

  useEffect(() => {
    const fetchRatings = async () => {
      try {
        const response = await fetch('http://localhost:8000/ratings/', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        if (response.ok) {
          const allRatings = await response.json();
          const avgRatings: { [id: number]: { total: number; count: number } } = {};
          allRatings.forEach((r: any) => {
            if (!avgRatings[r.recommendation_id]) {
              avgRatings[r.recommendation_id] = { total: 0, count: 0 };
            }
            avgRatings[r.recommendation_id].total += r.rating;
            avgRatings[r.recommendation_id].count += 1;
          });

          const finalAvgRatings: { [id: number]: { avg: number; count: number } } = {};
          for (const id in avgRatings) {
            finalAvgRatings[id] = {
              avg: avgRatings[id].total / avgRatings[id].count,
              count: avgRatings[id].count
            };
          }
          setAverageRatings(finalAvgRatings);
        }
      } catch (error) {
        console.error('Failed to fetch ratings:', error);
      }
    };

    if (token) {
      fetchRatings();
    }
  }, [token]);



  const handleRatingSubmit = async (recommendationId: number, recommendationName: string) => {
    try {
      const response = await fetch('http://localhost:8000/ratings/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          recommendation_id: recommendationId,
          rating: ratings[recommendationId],
          comment: comments[recommendationId]
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to submit rating');
      }

      alert('Thank you for your feedback!');
    } catch (error) {
      console.error('Error submitting rating:', error);
      alert('Failed to submit feedback. Please try again.');
    }
  };

  if (isLoading) {
    return (
      <div className="text-center">
        <Spinner animation="border" role="status">
          <span className="visually-hidden">Loading...</span>
        </Spinner>
        <p>Loading recommendations...</p>
      </div>
    );
  }

  if (!recommendations) {
    return (
      <Alert variant="warning">
        No recommendations found. Please <Link to="/form">fill out the form</Link> to get your recommendations.
      </Alert>
    );
  }

  return (
    <div className="printable-area">
      <Alert variant="success">
        <Row>
            <Col md={10}>
                <Alert.Heading>Analysis Complete!</Alert.Heading>
                <p>Your calculated average points: <strong>{recommendations.average_points.toFixed(2)}</strong> | Your Profile Rating: <strong>{recommendations.profile_rating}</strong></p>
                <p className="mb-0">Based on your profile, the most suitable course is <strong>{topCourse?.name}</strong> and career is <strong>{topCareer?.name}</strong>. This recommendation is generated by a model with an accuracy of <strong>{(recommendations.model_accuracy * 100).toFixed(0)}%</strong>.</p>
            </Col>
            <Col md={2} className="d-flex align-items-center justify-content-end">
                <Button variant="outline-success" onClick={() => window.print()} className="no-print">Download Report</Button>
            </Col>
        </Row>
      </Alert>

      <Row>
        <Col md={6} className="mb-4">
            <Card><Card.Body><GradesChart data={recommendations.subject_grades_points} /></Card.Body></Card>
        </Col>
        <Col md={6} className="mb-4">
            <Card><Card.Body><CoursesChart data={recommendations.courses} /></Card.Body></Card>
        </Col>
      </Row>

      <Row>
        <Col md={6}>
          <h2>Course Recommendations</h2>
          <Accordion defaultActiveKey="0">
            {recommendations.courses.map((course, index) => (
              <Accordion.Item eventKey={String(index)} key={index}>
                <Accordion.Header>
                  {course.name}
                  {averageRatings[course.id!] && (
                    <Badge bg="info" className="ms-2">
                      Avg: {averageRatings[course.id!].avg.toFixed(1)} ({averageRatings[course.id!].count} ratings)
                    </Badge>
                  )}
                  <div className="ms-auto" style={{ width: '100px' }}>
                    <ProgressBar now={(course.similarity_score * 100)} label={`${(course.similarity_score * 100).toFixed(0)}%`} />
                  </div>
                </Accordion.Header>
                <Accordion.Body>
                  <p><em>{course.description}</em></p>
                  <hr />
                  <DetailRow title="Course Type" content={course.course_type || 'N/A'} />
                  <DetailRow title="Why it's recommended" content={course.reasoning} />
                  <DetailRow title="Job Applicability" content={course.job_applicability} />
                  <DetailRow title="Future Trends" content={course.future_trends} />
                  <DetailRow title="Automation Risk" content={course.automation_risk} />
                  <hr />
                  <h5>Rate this recommendation</h5>
                  <StarRating
                    rating={ratings[course.id!] || 0}
                    setRating={(rating) => setRatings({ ...ratings, [course.id!]: rating })}
                  />
                  <Form.Group className="mt-3">
                    <Form.Label>Comments</Form.Label>
                    <Form.Control
                      as="textarea"
                      rows={3}
                      value={comments[course.id!] || ''}
                      onChange={(e) => setComments({ ...comments, [course.id!]: e.target.value })}
                    />
                  </Form.Group>
                  <Button
                    variant="primary"
                    className="mt-3"
                    onClick={() => handleRatingSubmit(course.id!, course.name)}
                  >
                    Submit Feedback
                  </Button>
                </Accordion.Body>
              </Accordion.Item>
            ))}
          </Accordion>
        </Col>
        <Col md={6}>
          <h2>Career Recommendations</h2>
          <Accordion defaultActiveKey="0">
            {recommendations.careers.map((career, index) => (
              <Accordion.Item eventKey={String(index)} key={index}>
                <Accordion.Header>
                  {career.name}
                  {averageRatings[career.id!] && (
                    <Badge bg="info" className="ms-2">
                      Avg: {averageRatings[career.id!].avg.toFixed(1)} ({averageRatings[career.id!].count} ratings)
                    </Badge>
                  )}
                  <div className="ms-auto" style={{ width: '100px' }}>
                    <ProgressBar now={(career.similarity_score * 100)} label={`${(career.similarity_score * 100).toFixed(0)}%`} />
                  </div>
                </Accordion.Header>
                <Accordion.Body>
                  <p><em>{career.description}</em></p>
                  <hr />
                  <DetailRow title="Why it's recommended" content={career.reasoning} />
                  <DetailRow title="Job Applicability" content={career.job_applicability} />
                  <DetailRow title="Future Trends" content={career.future_trends} />
                  <DetailRow title="Automation Risk" content={career.automation_risk} />
                  <hr />
                  <h5>Rate this recommendation</h5>
                  <StarRating
                    rating={ratings[career.id!] || 0}
                    setRating={(rating) => setRatings({ ...ratings, [career.id!]: rating })}
                  />
                  <Form.Group className="mt-3">
                    <Form.Label>Comments</Form.Label>
                    <Form.Control
                      as="textarea"
                      rows={3}
                      value={comments[career.id!] || ''}
                      onChange={(e) => setComments({ ...comments, [career.id!]: e.target.value })}
                    />
                  </Form.Group>
                  <Button
                    variant="primary"
                    className="mt-3"
                    onClick={() => handleRatingSubmit(career.id!, career.name)} // Pass career.id
                  >
                    Submit Feedback
                  </Button>
                </Accordion.Body>
              </Accordion.Item>
            ))}
          </Accordion>
        </Col>
      </Row>
    </div>
  );
};

export default ReportPage;